//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace CatFact.Infrastructures.Services
{
    public interface ICatFactService
    {
        string BaseUrl { get; set; }
        bool ReadResponseAsString { get; set; }

        Task<ICollection<Breed>> GetBreedsAsync(long? limit);
        Task<ICollection<Breed>> GetBreedsAsync(long? limit, CancellationToken cancellationToken);
        Task<ICollection<CatFact>> GetFactsAsync(long? max_length, long? limit);
        Task<ICollection<CatFact>> GetFactsAsync(long? max_length, long? limit, CancellationToken cancellationToken);
        Task<CatFact> GetRandomFactAsync(long? max_length);
        Task<CatFact> GetRandomFactAsync(long? max_length, CancellationToken cancellationToken);
    }
}